"""
scripts/databricks_deploy.py
Crée et lance automatiquement le notebook Silver sur Databricks via API REST.
"""

import requests
import json
import base64
import os
import time
from dotenv import load_dotenv

load_dotenv()

DATABRICKS_HOST  = "https://adb-7405609147419690.10.azuredatabricks.net"
DATABRICKS_TOKEN = os.getenv("DATABRICKS_TOKEN")
CLUSTER_ID       = "0507-054438-mj871702"
NOTEBOOK_PATH    = "/Users/ashraf.jemali@gmail.com/silver_clickstream_pubsub"

HEADERS = {
    "Authorization": f"Bearer {DATABRICKS_TOKEN}",
    "Content-Type":  "application/json",
}

NOTEBOOK_CODE = '''
# Databricks Silver Clickstream Job
# Auto-generated by scripts/databricks_deploy.py

# ── Cellule 1 : Config GCP ──────────────────────────────────────
spark.conf.set("fs.gs.auth.service.account.enable", "true")
spark.conf.set("fs.gs.project.id", "projet-dbt-495310")
print("GCP config OK")

# ── Cellule 2 : Lecture Bronze GCS ──────────────────────────────
BRONZE_PATH = "gs://dataflow-dev-bronze/clickstream/"
SILVER_PATH = "gs://dataflow-dev-silver/clickstream/"
DATE        = "2026-05-11"

df_bronze = spark.read.parquet(f"{BRONZE_PATH}date={DATE}/")
print(f"Bronze records: {df_bronze.count():,}")
df_bronze.printSchema()
df_bronze.show(5, truncate=True)

# ── Cellule 3 : Transformations Silver ──────────────────────────
from pyspark.sql import functions as F

df_silver = (
    df_bronze
    # Cast types
    .withColumn("event_type",   F.lower(F.trim(F.col("event_type"))))
    .withColumn("device_type",  F.lower(F.trim(F.col("device_type"))))
    .withColumn("country_code", F.upper(F.trim(F.col("country_code"))))
    # Parse timestamp
    .withColumn("event_ts", F.to_timestamp(F.col("event_timestamp")))
    .withColumn("event_date", F.to_date(F.col("event_ts")))
    # Filter invalid
    .filter(F.col("event_id").isNotNull())
    .filter(F.col("event_type").isin([
        "page_view","product_view","add_to_cart","remove_from_cart",
        "checkout_start","purchase","search","session_start"
    ]))
    .filter(
        F.col("user_id").isNotNull() | F.col("anonymous_id").isNotNull()
    )
    # Dedup
    .dropDuplicates(["event_id"])
    # IP anonymisation GDPR
    .withColumn(
        "ip_anonymized",
        F.regexp_replace(F.col("ip_address"), r"\\.\\d+$", ".0")
    )
    .drop("ip_address")
    # Revenue normalisation
    .withColumn(
        "revenue_eur",
        F.when(
            F.col("revenue").isNotNull(),
            F.regexp_replace(
                F.regexp_replace(F.col("revenue"), r"[€$£]|EUR|USD|GBP", ""),
                ",", "."
            ).cast("double")
        ).otherwise(0.0)
    )
    .withColumn("has_revenue", F.col("revenue_eur") > 0)
    .drop("revenue")
    # Metadata
    .withColumn("_silver_processed_at", F.current_timestamp())
    .withColumn("_processing_date", F.lit(DATE))
)

print(f"Silver records: {df_silver.count():,}")
df_silver.show(5, truncate=True)

# ── Cellule 4 : Écriture Silver GCS (Delta) ─────────────────────
(
    df_silver
    .repartition(4)
    .write
    .format("parquet")
    .mode("overwrite")
    .partitionBy("event_date", "event_type")
    .save(SILVER_PATH)
)
print(f"✓ Silver written to {SILVER_PATH}")

# ── Cellule 5 : Résumé ──────────────────────────────────────────
summary = (
    df_silver
    .groupBy("event_type", "country_code", "device_type")
    .agg(
        F.count("*").alias("event_count"),
        F.sum("revenue_eur").alias("total_revenue_eur"),
        F.countDistinct("user_id").alias("unique_users")
    )
    .orderBy(F.col("event_count").desc())
)
summary.show(20)
print("✓ Silver job complete!")
'''


def create_notebook() -> None:
    """Crée le notebook sur Databricks via API."""
    content_b64 = base64.b64encode(NOTEBOOK_CODE.encode()).decode()
    payload = {
        "path":      NOTEBOOK_PATH,
        "language":  "PYTHON",
        "content":   content_b64,
        "overwrite": True,
        "format":    "SOURCE",
    }
    resp = requests.post(
        f"{DATABRICKS_HOST}/api/2.0/workspace/import",
        headers=HEADERS,
        json=payload,
    )
    resp.raise_for_status()
    print(f"✓ Notebook créé : {NOTEBOOK_PATH}")


def start_cluster() -> None:
    """Démarre le cluster si arrêté."""
    resp = requests.get(
        f"{DATABRICKS_HOST}/api/2.0/clusters/get",
        headers=HEADERS,
        params={"cluster_id": CLUSTER_ID},
    )
    state = resp.json().get("state", "UNKNOWN")
    print(f"Cluster state: {state}")

    if state == "TERMINATED":
        print("Démarrage du cluster...")
        requests.post(
            f"{DATABRICKS_HOST}/api/2.0/clusters/start",
            headers=HEADERS,
            json={"cluster_id": CLUSTER_ID},
        )
        # Attendre que le cluster soit RUNNING
        for _ in range(30):
            time.sleep(10)
            resp  = requests.get(
                f"{DATABRICKS_HOST}/api/2.0/clusters/get",
                headers=HEADERS,
                params={"cluster_id": CLUSTER_ID},
            )
            state = resp.json().get("state")
            print(f"  Cluster state: {state}")
            if state == "RUNNING":
                print("✓ Cluster RUNNING")
                return
        raise TimeoutError("Cluster did not start in 5 minutes")
    elif state == "RUNNING":
        print("✓ Cluster already RUNNING")


def run_notebook() -> str:
    """Lance le notebook et retourne le run_id."""
    payload = {
        "run_name":           "silver_clickstream_pubsub",
        "existing_cluster_id": CLUSTER_ID,
        "notebook_task": {
            "notebook_path": NOTEBOOK_PATH,
            "base_parameters": {
                "date":        "2026-05-11",
                "bronze_path": "gs://dataflow-dev-bronze/clickstream/",
                "silver_path": "gs://dataflow-dev-silver/clickstream/",
            },
        },
    }
    resp = requests.post(
        f"{DATABRICKS_HOST}/api/2.0/jobs/runs/submit",
        headers=HEADERS,
        json=payload,
    )
    resp.raise_for_status()
    run_id = resp.json()["run_id"]
    print(f"✓ Job lancé — run_id: {run_id}")
    return str(run_id)


def wait_for_run(run_id: str) -> str:
    """Attend la fin du job et retourne le status."""
    print(f"Waiting for run {run_id}...")
    for _ in range(60):
        time.sleep(15)
        resp  = requests.get(
            f"{DATABRICKS_HOST}/api/2.0/jobs/runs/get",
            headers=HEADERS,
            params={"run_id": run_id},
        )
        state = resp.json()["state"]["life_cycle_state"]
        result = resp.json()["state"].get("result_state", "")
        print(f"  Run state: {state} {result}")
        if state == "TERMINATED":
            if result == "SUCCESS":
                print("✓ Job SUCCESS !")
            else:
                print(f"✗ Job FAILED : {result}")
            return result
    raise TimeoutError("Job did not finish in 15 minutes")


if __name__ == "__main__":
    print("=== Databricks Silver Job Deploy ===")
    create_notebook()
    start_cluster()
    run_id = run_notebook()
    wait_for_run(run_id)
    print("\n=== DONE ===")
    print(f"Notebook : {DATABRICKS_HOST}/#notebook{NOTEBOOK_PATH}")
    print(f"Silver   : gs://dataflow-dev-silver/clickstream/")